language: cpp
compiler:
  - gcc
  - clang
script: make
addons:
  apt:
    packages:
    - libboost-dev 
    - libboost-test-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-regex-dev
    - libboost-thread-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..