sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
cache:
  apt: true
addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - cmake
      - g++-5
      - gcc-5
      - libboost1.55-all-dev
      - llvm-3.8-dev
      - llvm-3.8-runtime
      - llvm-3.8-tools"
script:
  - test -d build || mkdir build
  - cd build
  - cmake ..
  - make
  - make test
