sudo: false
language: cpp
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - export BOOST_ROOT=~/libboost_1_59_0/usr
  - /bin/bash travis_install_boost.sh || { rm -rf "$BOOST_ROOT" ; exit 1; }
cache:
  directories:
    - ~/libboost_1_59_0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-5
      - gcc-5

script:
  - test -d build || mkdir build
  - cd build
  - cmake ..
  - make
  - make test
