sudo: false

language: cpp

compiler:
  - gcc
  - clang
install:
  - export BOOST_BASE="~/libboost_1_60_0"
  - if [ "${CXX}" = "g++" ]; then export CXX="g++-5" CC="gcc-5" BOOST_CXX="g++-5" BOOST_ROOT="${BOOST_BASE}/usr" BOOST_SH="travis_install_boost.sh"; fi
  - if [ "${CXX}" = "clang++" ]; then export BOOST_ROOT="${BOOST_BASE}_clang/usr" BOOST_CXX="clang++"  BOOST_SH="travis_install_boost_clang.sh"; fi
  - /bin/bash "${BOOST_SH}" || { rm -rf "${BOOST_ROOT}" ; exit 1; }

cache:
  directories:
    - ~/libboost_1_60_0
    - ~/libboost_1_60_0_clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang
      - libc++
      - g++-5
      - gcc-5
      - libbz2-dev
      - libssl-dev
      - git

script:
  - test -d build || mkdir build
  - cd build
  - cmake ..
  - make
  - make test
