sudo: false
language: cpp
compiler:
  - gcc
  - clang
script: make
cache:
  apt: true
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost1.55.-all-dev 
before_script:
  - mkdir build
  - cd build
  - cmake ..