sudo: false
language: cpp
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; ln -sf /usr/bin/gcc-5 /usr/bin/gcc; ln -sf /usr/bin/g++-5 /usr/bin/g++; fi
  - wget -O boost_1_59_0.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2/download
  - tar -xjf boost_1_59_0.tar.bz2
  - cd boost_1_59_0 && ./bootstrap.sh --prefix=~/libboost_1_59_0 && ./b2 -d0 -q install && export BOOST_ROOT=~/libboost_1_59_0
cache:
  directories:
    - ~/libboost_1_59_0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-5
      - gcc-5

script:
  - test -d build || mkdir build
  - cd build
  - cmake ..
  - make
  - make test
