sudo: false
language: cpp
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" BOOST_CXX="g++-5"; else export BOOST_CXX="g++"; fi
  - export BOOST_ROOT=~/libboost_1_59_0/usr
  - /bin/bash travis_install_boost.sh || { rm -rf "$BOOST_ROOT" ; exit 1; }
cache:
  directories:
    - ~/libboost_1_59_0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-5
      - gcc-5
<<<<<<< HEAD
	  - libbz2-dev
	  - libssl-dev
=======
      - git
>>>>>>> 425ee9751cd145f1bc506fd10f4766de744a66fb

script:
  - test -d build || mkdir build
  - cd build
  - cmake ..
  - make
  - make test
