sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - g++-5
      - gcc-5
      - libboost1.55-all-dev
      - libc++-dev
      - libstdc++-dev

script:
  - test -d build || mkdir build
  - cd build
  - cmake ..
  - make
  - make test
