language: cpp
compiler:
  - gcc
  - clang
script: cmake . && make && make test
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-test-dev libboost-filesystem-dev libboost-system-dev libboost-regex-dev libboost-thread-dev
  - sudo dpkg -S /usr/include/boost/version.hpp
